// This code is generated by {rx-platform} Code Generation Tool
// DO NOT MODIFY THIS CODE, it can be recreated

using ENSACO.RxPlatform.Attributes;
using ENSACO.RxPlatform.Model.System;

namespace ENSACO.RxPlatform.Model.RNP
{
public class BekaClearSource : BekaDisplaySource
{
	public BekaClearSource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true)
		: base(nodeId == "" ? "1:g:b557657f-82ee-44ae-9bbe-a7cde54cf1b6" : nodeId, directory == "" ? "/sys/plugins/mesrnp" : directory, name == "" ? "BekaClearSource" : name, Element == "" ? "BekaClearSource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
	}

}
public class BekaDirectSource : BekaDisplaySource
{
	public BekaDirectSource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true)
		: base(nodeId == "" ? "1:g:4b3f778b-c0b3-4c61-8ed0-0c2a882e26a2" : nodeId, directory == "" ? "/sys/plugins/mesrnp" : directory, name == "" ? "BekaDirectSource" : name, Element == "" ? "BekaDirectSource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
	}

}
[RxPlatformPortType(nodeId: "1:g:3da25b12-3a4e-4825-8b6a-1ac50c922fbe",  directory: "/sys/plugins/mesrnp",  name: "BekaDisplayConnection")]
public class BekaDisplayConnection : ApplicationPort
{
	public MasterTimeoutsData Timeouts { get; set; } = new MasterTimeoutsData();
	public new MasterPortStatusData Status { get; set; } = new MasterPortStatusData();
}
public class BekaDisplayRelation : PortReference
{
	protected BekaDisplayRelation(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public BekaDisplayRelation()
		: base("1:g:49a306da-2a00-4148-9975-741a3314e97b", "/sys/plugins/mesrnp", "BekaDisplayRelation")
	{
	}

}
public class BekaDisplaySource : ExternSource
{
	public BekaDisplaySource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true)
		: base(nodeId == "" ? "1:g:2f7177e8-a6fa-4865-b7e9-de28ccbf22a0" : nodeId, directory == "" ? "/sys/plugins/mesrnp" : directory, name == "" ? "BekaDisplaySource" : name, Element == "" ? "BekaDisplaySource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
	}

}
public class BekaTextSource : BekaDisplaySource
{
	public BekaTextSource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true)
		: base(nodeId == "" ? "1:g:4c94ee56-c642-4b08-9280-4075379bb596" : nodeId, directory == "" ? "/sys/plugins/mesrnp" : directory, name == "" ? "BekaTextSource" : name, Element == "" ? "BekaTextSource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
	}

}
[RxPlatformFilterType(nodeId: "1:g:38ea4f2b-17af-451c-9308-b3efd4fe23a3",  directory: "/sys/plugins/mesrnp",  name: "MercuryCardDataCorrect")]
public class MercuryCardDataCorrect : RxPlatformFilterAttribute
{
	public MercuryCardDataCorrect(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true)
		: base(nodeId == "" ? "1:g:38ea4f2b-17af-451c-9308-b3efd4fe23a3" : nodeId, directory == "" ? "/sys/plugins/mesrnp" : directory, name == "" ? "MercuryCardDataCorrect" : name, Element == "" ? "MercuryCardDataCorrect" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
	}

}
}
// Generated on:Friday, October 2, 2026  9:05:48 AM
