<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RxPlatform.Hosting</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <EnableUnmanagedExports>true</EnableUnmanagedExports>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Version>3.3.1</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>{rx-platform} .NET Core Host</Title>
    <Authors>ENSACO Solutions doo</Authors>
    <Company>ENSACO Solutions doo</Company>
    <Product>{rx-platform}</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) 2026 ENSACO Solutions doo</Copyright>
    <PackageProjectUrl>http://rx-platform.org/</PackageProjectUrl>
    <Description>Package that {rx-platform} uses as .NET Core hosting library.</Description>
    <PackageIcon>rx-platform-256.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Images\Logo\rx-platform-256.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ENSACO.RxPlatform.Attributes\ENSACO.RxPlatform.csproj">
      <Private>True</Private>
    </ProjectReference>
    <ProjectReference Include="..\ENSACO.RxPlatform.Modbus\ENSACO.RxPlatform.Modbus.csproj" />
  </ItemGroup>
  
</Project>
