// This code is generated by {rx-platform} Code Generation Tool
// DO NOT MODIFY THIS CODE, it can be recreated

using ENSACO.RxPlatform.Attributes;
using ENSACO.RxPlatform.Model.System;

namespace ENSACO.RxPlatform.Model.System
{
[RxPlatformDataType(nodeId: "1:i:21",  directory: "/sys/types/base",  name: "DataTypeBase")]
public class DataTypeBase
{
}
[RxPlatformDataType(nodeId: "1:i:201326831",  directory: "/sys/types/system",  name: "BucketStatus")]
public class BucketStatus
{
	public ulong BucketSize { get; set; } = 0;
	public ulong Used { get; set; } = 0;
	public ulong Free { get; set; } = 0;
	public ulong Capacity { get; set; } = 0;
	public ulong MaxUsed { get; set; } = 0;
}
[RxPlatformDataType(nodeId: "1:i:201326671",  directory: "/sys/types/system",  name: "ItemChangeDetails")]
public class ItemChangeDetails
{
	public DateTime TS { get; set; } = DateTime.Parse("2025-12-09T14:12:06.665");
	public RxNodeId Id { get; set; } = RxNodeId.FromString("");
	public string Path { get; set; } = "";
}
[RxPlatformDataType(nodeId: "1:i:201326832",  directory: "/sys/types/system",  name: "MemoryStatus")]
public class MemoryStatus
{
	public ulong Total { get; set; } = 0;
	public ulong Used { get; set; } = 0;
	public double Percent { get; set; } = 0;
	public ulong Delta { get; set; } = 0;
	public ulong DbgVal { get; set; } = 0;
	public BucketStatus[] Buckets { get; set; } = new BucketStatus[0];
}
[RxPlatformDataType(nodeId: "1:i:25",  directory: "/sys/types/term",  name: "ConsoleInData")]
public class ConsoleInData
{
	public string In { get; set; } = "";
}
[RxPlatformDataType(nodeId: "1:i:26",  directory: "/sys/types/term",  name: "ConsoleOUTData")]
public class ConsoleOUTData
{
	public string Out { get; set; } = "";
	public string Err { get; set; } = "";
	public bool Result { get; set; } = false;
}
[RxPlatformEventType(nodeId: "1:i:7",  directory: "/sys/types/base",  name: "EventBase")]
public class EventBase
{
}
[RxPlatformObjectType(nodeId: "1:i:201326655",  directory: "/sys/types/base",  name: "InternalObjectType")]
public class InternalObjectType : ObjectBase
{
}
[RxPlatformMapperType(nodeId: "1:i:9",  directory: "/sys/types/base",  name: "MapperBase")]
public class MapperBase
{
}
[RxPlatformObjectType(nodeId: "1:i:1",  directory: "/sys/types/base",  name: "ObjectBase")]
public class ObjectBase
{
}
[RxPlatformEventType(nodeId: "1:i:28",  directory: "/sys/types/base",  name: "ObjectChanged")]
public class ObjectChanged
{
}
[RxPlatformStructType(nodeId: "1:i:13",  directory: "/sys/types/base",  name: "ObjectData")]
public class ObjectData
{
	public string PID { get; set; } = "";
	public string Description { get; set; } = "";
	public string Note { get; set; } = "";
	public double LastScanTime { get; set; } = 0;
	public uint LoopCount { get; set; } = 0;
	public double MaxScanTime { get; set; } = 0;
	public uint ProcessSlots { get; set; } = 0;
	public bool On { get; set; } = true;
	public bool Test { get; set; } = false;
	public bool Blocked { get; set; } = false;
	public bool Simulate { get; set; } = false;
	public bool SimActive { get; set; } = false;
}
[RxPlatformPortType(nodeId: "1:i:4",  directory: "/sys/types/base",  name: "PortBase")]
public class PortBase
{
	public PortOptions Options { get; set; } = new PortOptions();
	public PortStatusData Status { get; set; } = new PortStatusData();
}
[RxPlatformStructType(nodeId: "1:i:201326689",  directory: "/sys/types/base",  name: "PortOptions")]
public class PortOptions
{
	public uint BuffBackCapacity { get; set; } = 256;
	public uint BuffFrontCapacity { get; set; } = 16;
	public uint BuffDiscardSize { get; set; } = 4096;
}
[RxPlatformStructType(nodeId: "1:i:201326617",  directory: "/sys/types/base",  name: "PortStatusData")]
public class PortStatusData
{
	public bool BindedUp { get; set; } = false;
	public bool BindedDown { get; set; } = false;
	public bool Assembled { get; set; } = false;
	public short Endpoints { get; set; } = 0;
	public long RxPackets { get; set; } = 0;
	public long TxPackets { get; set; } = 0;
	public uint Buffers { get; set; } = 0;
	public long DropedBuffers { get; set; } = 0;
}
public class RelationBase : RxPlatformRelationAttribute
{
	protected RelationBase(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public RelationBase()
		: base("1:i:14", "/sys/types/base", "RelationBase")
	{
	}

}
[RxPlatformSourceType(nodeId: "1:i:8",  directory: "/sys/types/base",  name: "SourceBase")]
public class SourceBase
{
}
[RxPlatformStructType(nodeId: "1:i:5",  directory: "/sys/types/base",  name: "StructBase")]
public class StructBase
{
}
[RxPlatformObjectType(nodeId: "1:i:201326652",  directory: "/sys/types/base",  name: "UserObject")]
public class UserObject : ObjectBase
{
}
[RxPlatformStructType(nodeId: "1:i:201326678",  directory: "/sys/types/system",  name: "HostInfo")]
public class HostInfo
{
	public string HostVer { get; set; } = "";
	public string OSHostVer { get; set; } = "";
	public string FirmwareVer { get; set; } = "";
	public string OSVer { get; set; } = "";
	public string CPU { get; set; } = "";
	public uint CPUCores { get; set; } = 0;
	public bool LittleEndian { get; set; } = false;
	public ulong MemoryTotal { get; set; } = 0;
	public ulong MemoryFree { get; set; } = 0;
	public uint PageSize { get; set; } = 0;
}
[RxPlatformObjectType(nodeId: "1:i:201326679",  directory: "/sys/types/system",  name: "HostType")]
public class HostType : InternalObjectType
{
	public HostInfo Info { get; set; } = new HostInfo();
}
[RxPlatformPortType(nodeId: "1:i:201326824",  directory: "/sys/types/system",  name: "HttpAddressingPort")]
public class HttpAddressingPort : TransportPort
{
	public new HttpAddressingPortOptions Options { get; set; } = new HttpAddressingPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326826",  directory: "/sys/types/system",  name: "HttpHostNamePort")]
public class HttpHostNamePort : ConnectionTransportPort
{
	public new HttpAddressingPortOptions Options { get; set; } = new HttpAddressingPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326673",  directory: "/sys/types/system",  name: "HttpProtocol")]
public class HttpProtocol : ApplicationPort
{
}
[RxPlatformObjectType(nodeId: "1:i:201326597",  directory: "/sys/types/system",  name: "IoManagerType")]
public class IoManagerType : InternalObjectType
{
}
[RxPlatformObjectType(nodeId: "1:i:201326599",  directory: "/sys/types/system",  name: "IoPoolType")]
public class IoPoolType : InternalObjectType
{
	public PoolData Pool { get; set; } = new PoolData();
}
[RxPlatformEventType(nodeId: "1:i:201326672",  directory: "/sys/types/system",  name: "ItemChangeEvent")]
public class ItemChangeEvent
{
}
[RxPlatformObjectType(nodeId: "1:i:201326601",  directory: "/sys/types/system",  name: "LogType")]
public class LogType : InternalObjectType
{
}
[RxPlatformObjectType(nodeId: "1:i:201326830",  directory: "/sys/types/system",  name: "MemoryType")]
public class MemoryType : InternalObjectType
{
	public MemoryStatus Status { get; set; } = new MemoryStatus();
}
[RxPlatformObjectType(nodeId: "1:i:201326633",  directory: "/sys/types/system",  name: "MetaThreadType")]
public class MetaThreadType : PhysicalThread
{
}
[RxPlatformObjectType(nodeId: "1:i:201326766",  directory: "/sys/types/system",  name: "PeerConnection")]
public class PeerConnection : InternalObjectType
{
	public PeerEndpoint Endpoint { get; set; } = new PeerEndpoint();
	public PeerStatus Status { get; set; } = new PeerStatus();
	[RxJsonProtocolClient()]
	public RxJsonClientProtocol? Conn { get; set; } = null;
}
[RxPlatformObjectType(nodeId: "1:i:201326641",  directory: "/sys/types/system",  name: "PhysicalThread")]
public class PhysicalThread : InternalObjectType
{
	public ThreadData Thread { get; set; } = new ThreadData();
	public PoolData Pool { get; set; } = new PoolData();
}
[RxPlatformObjectType(nodeId: "1:i:201326596",  directory: "/sys/types/system",  name: "RuntimeType")]
public class RuntimeType : InternalObjectType
{
	public RuntimeData Runtime { get; set; } = new RuntimeData();
}
[RxPlatformPortType(nodeId: "1:i:201326729",  directory: "/sys/types/system",  name: "RxJsonClientProtocol")]
public class RxJsonClientProtocol : ApplicationPort
{
	public OpcEndpointBindData Connect { get; set; } = new OpcEndpointBindData();
	public new ClientPortStatusData Status { get; set; } = new ClientPortStatusData();
}
[RxPlatformPortType(nodeId: "1:i:201326626",  directory: "/sys/types/system",  name: "RxJsonProtocol")]
public class RxJsonProtocol : ApplicationPort
{
}
public class RxJsonProtocolClient : PortReference
{
	protected RxJsonProtocolClient(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public RxJsonProtocolClient()
		: base("1:i:201326769", "/sys/types/system", "RxJsonProtocolClient")
	{
	}

}
[RxPlatformPortType(nodeId: "1:i:201326864",  directory: "/sys/types/system",  name: "RxOPCProtocolAdapter")]
public class RxOPCProtocolAdapter : TransportPort
{
	public OpcEndpointBindData Bind { get; set; } = new OpcEndpointBindData();
}
[RxPlatformPortType(nodeId: "1:i:201326680",  directory: "/sys/types/system",  name: "SystemHttpPort")]
public class SystemHttpPort : TCPServerPort
{
}
[RxPlatformStructType(nodeId: "1:i:201326677",  directory: "/sys/types/system",  name: "SystemInfo")]
public class SystemInfo
{
	public string Instance { get; set; } = "";
	public string Node { get; set; } = "";
	public DateTime StartTime { get; set; } = DateTime.Parse("2025-12-09T14:12:05.022");
	public DateTime Time { get; set; } = DateTime.Parse("2025-12-09T14:12:06.664");
	public string PlatformVer { get; set; } = "";
	public string LibraryVer { get; set; } = "";
	public string TerminalVer { get; set; } = "";
	public string HttpVer { get; set; } = "";
	public string CompilerVer { get; set; } = "";
}
[RxPlatformPortType(nodeId: "1:i:201326835",  directory: "/sys/types/system",  name: "SystemMqttPort")]
public class SystemMqttPort : TCPClientPort
{
}
[RxPlatformPortType(nodeId: "1:i:201326724",  directory: "/sys/types/system",  name: "SystemOpcPort")]
public class SystemOpcPort : TCPServerPort
{
}
[RxPlatformPortType(nodeId: "1:i:201326681",  directory: "/sys/types/system",  name: "SystemRxPort")]
public class SystemRxPort : TCPServerPort
{
}
[RxPlatformPortType(nodeId: "1:i:201326857",  directory: "/sys/types/system",  name: "SystemRxWSPort")]
public class SystemRxWSPort : TCPServerPort
{
}
[RxPlatformObjectType(nodeId: "1:i:201326676",  directory: "/sys/types/system",  name: "SystemType")]
public class SystemType : InternalObjectType
{
	public SystemInfo Info { get; set; } = new SystemInfo();
}
[RxPlatformPortType(nodeId: "1:i:201326862",  directory: "/sys/types/system",  name: "SystemWsJsonPort")]
public class SystemWsJsonPort : RxJsonProtocol
{
	public PathBindData Bind { get; set; } = new PathBindData();
}
[RxPlatformObjectType(nodeId: "1:i:201326632",  directory: "/sys/types/system",  name: "UnassignedThreadType")]
public class UnassignedThreadType : PhysicalThread
{
}
[RxPlatformPortType(nodeId: "1:i:201326772",  directory: "/sys/types/system",  name: "WSProtocol")]
public class WSProtocol : ConnectionTransportPort
{
}
[RxPlatformPortType(nodeId: "1:i:201326606",  directory: "/sys/types/ports",  name: "ApplicationPort")]
public class ApplicationPort : PortBase
{
	[PortStack()]
	public PortBase? StackTop { get; set; } = null;
}
[RxPlatformPortType(nodeId: "1:i:201326683",  directory: "/sys/types/ports",  name: "ByteRouterPort")]
public class ByteRouterPort : RoutedTransportPort
{
	public new RouterPortOptions Options { get; set; } = new RouterPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326756",  directory: "/sys/types/ports",  name: "ConnectionTransportPort")]
public class ConnectionTransportPort : PortBase
{
	[PortStack()]
	public PortBase? StackTop { get; set; } = null;
}
[RxPlatformPortType(nodeId: "1:i:201326614",  directory: "/sys/types/ports",  name: "EthernetPort")]
public class EthernetPort : ExternalPort
{
	public new EthernetPortOptions Options { get; set; } = new EthernetPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326604",  directory: "/sys/types/ports",  name: "ExternalPort")]
public class ExternalPort : PortBase
{
	public new ExternalPortStatusData Status { get; set; } = new ExternalPortStatusData();
}
[RxPlatformPortType(nodeId: "1:i:201326844",  directory: "/sys/types/ports",  name: "FilePort")]
public class FilePort : ExternalPort
{
	public new FilePortOptions Options { get; set; } = new FilePortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326682",  directory: "/sys/types/ports",  name: "IP4RouterPort")]
public class IP4RouterPort : RoutedTransportPort
{
	public new RouterPortOptions Options { get; set; } = new RouterPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326700",  directory: "/sys/types/ports",  name: "Initiator2ListenerPort")]
public class Initiator2ListenerPort : RoutedTransportPort
{
}
[RxPlatformPortType(nodeId: "1:i:201326701",  directory: "/sys/types/ports",  name: "Listener2InitiatorPort")]
public class Listener2InitiatorPort : RoutedTransportPort
{
}
[RxPlatformPortType(nodeId: "1:i:201326764",  directory: "/sys/types/ports",  name: "MACRouterPort")]
public class MACRouterPort : RoutedTransportPort
{
	public new RouterPortOptions Options { get; set; } = new RouterPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326648",  directory: "/sys/types/ports",  name: "RoutedTransportPort")]
public class RoutedTransportPort : PortBase
{
	[PortStack()]
	public PortBase? StackTop { get; set; } = null;
}
[RxPlatformPortType(nodeId: "1:i:201326698",  directory: "/sys/types/ports",  name: "STXETXPort")]
public class STXETXPort : TransportPort
{
	public new STXETXPortOptions Options { get; set; } = new STXETXPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326608",  directory: "/sys/types/ports",  name: "SerialPort")]
public class SerialPort : ExternalPort
{
	public new SerialPortOptions Options { get; set; } = new SerialPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326816",  directory: "/sys/types/ports",  name: "SizeLimiterPort")]
public class SizeLimiterPort : TransportPort
{
	public new PortStatusData Status { get; set; } = new PortStatusData();
	public new SizeLimiterPortOptions Options { get; set; } = new SizeLimiterPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326793",  directory: "/sys/types/ports",  name: "StringRouterPort")]
public class StringRouterPort : RoutedTransportPort
{
	public new RouterPortOptions Options { get; set; } = new RouterPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326613",  directory: "/sys/types/ports",  name: "TCPClientPort")]
public class TCPClientPort : ExternalPort
{
	public new TcpPortOptions Options { get; set; } = new TcpPortOptions();
	public IPBindData Connect { get; set; } = new IPBindData();
	public IPBindData Bind { get; set; } = new IPBindData();
	public ClientTimeoutsData Timeouts { get; set; } = new ClientTimeoutsData();
}
[RxPlatformPortType(nodeId: "1:i:201326612",  directory: "/sys/types/ports",  name: "TCPServerPort")]
public class TCPServerPort : ExternalPort
{
	public new TcpPortOptions Options { get; set; } = new TcpPortOptions();
	public IPBindData Bind { get; set; } = new IPBindData();
	public ServerTimeoutsData Timeouts { get; set; } = new ServerTimeoutsData();
}
[RxPlatformPortType(nodeId: "1:i:201326616",  directory: "/sys/types/ports",  name: "TelnetPort")]
public class TelnetPort : TransportPort
{
}
[RxPlatformPortType(nodeId: "1:i:201326774",  directory: "/sys/types/ports",  name: "TlsPortType")]
public class TlsPortType : ConnectionTransportPort
{
	public TlsPortTimeouts Timeouts { get; set; } = new TlsPortTimeouts();
	public new TlsPortStatus Status { get; set; } = new TlsPortStatus();
	public new TlsPortOptions Options { get; set; } = new TlsPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326684",  directory: "/sys/types/ports",  name: "TransactionLimiterPort")]
public class TransactionLimiterPort : TransportPort
{
	public MasterTimeoutsData Timeouts { get; set; } = new MasterTimeoutsData();
	public new MasterPortStatusData Status { get; set; } = new MasterPortStatusData();
	public new LimiterPortOptions Options { get; set; } = new LimiterPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326605",  directory: "/sys/types/ports",  name: "TransportPort")]
public class TransportPort : PortBase
{
	[PortStack()]
	public PortBase? StackTop { get; set; } = null;
}
[RxPlatformPortType(nodeId: "1:i:201326609",  directory: "/sys/types/ports",  name: "UDPPort")]
public class UDPPort : ExternalPort
{
	public IPBindData Bind { get; set; } = new IPBindData();
	public IPBindData MultiCast { get; set; } = new IPBindData();
}
[RxPlatformPortType(nodeId: "1:i:201326763",  directory: "/sys/types/ports",  name: "WordRouterPort")]
public class WordRouterPort : RoutedTransportPort
{
	public new RouterPortOptions Options { get; set; } = new RouterPortOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326735",  directory: "/sys/types/opc",  name: "OpcBinClientSecNone")]
public class OpcBinClientSecNone : OpcClientSecBase
{
}
[RxPlatformPortType(nodeId: "1:i:201326736",  directory: "/sys/types/opc",  name: "OpcBinClientSecSign")]
public class OpcBinClientSecSign : OpcClientSecBase
{
}
[RxPlatformPortType(nodeId: "1:i:201326737",  directory: "/sys/types/opc",  name: "OpcBinClientSecSignEncr")]
public class OpcBinClientSecSignEncr : OpcClientSecBase
{
}
[RxPlatformPortType(nodeId: "1:i:201326738",  directory: "/sys/types/opc",  name: "OpcBinClientSecSignSignEncr")]
public class OpcBinClientSecSignSignEncr : OpcClientSecBase
{
}
[RxPlatformPortType(nodeId: "1:i:201326715",  directory: "/sys/types/opc",  name: "OpcBinSecNone")]
public class OpcBinSecNone : OpcSecBase
{
}
[RxPlatformPortType(nodeId: "1:i:201326717",  directory: "/sys/types/opc",  name: "OpcBinSecSign")]
public class OpcBinSecSign : OpcSecBase
{
}
[RxPlatformPortType(nodeId: "1:i:201326718",  directory: "/sys/types/opc",  name: "OpcBinSecSignEncr")]
public class OpcBinSecSignEncr : OpcSecBase
{
}
[RxPlatformPortType(nodeId: "1:i:201326719",  directory: "/sys/types/opc",  name: "OpcBinSecSignSignEncr")]
public class OpcBinSecSignSignEncr : OpcSecBase
{
}
[RxPlatformPortType(nodeId: "1:i:201326642",  directory: "/sys/types/opc",  name: "OpcBinTransport")]
public class OpcBinTransport : TransportPort
{
	public new OpcBinTransportOptions Options { get; set; } = new OpcBinTransportOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326741",  directory: "/sys/types/opc",  name: "OpcClientBase")]
public class OpcClientBase : ApplicationPort
{
	public new OpcClientOptions Options { get; set; } = new OpcClientOptions();
	public OpcEndpointBindData Connect { get; set; } = new OpcEndpointBindData();
}
[RxPlatformPortType(nodeId: "1:i:201326745",  directory: "/sys/types/opc",  name: "OpcClientBinTransport")]
public class OpcClientBinTransport : TransportPort
{
	public new OpcClientBinTransportOptions Options { get; set; } = new OpcClientBinTransportOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326734",  directory: "/sys/types/opc",  name: "OpcClientSecBase")]
public class OpcClientSecBase : ConnectionTransportPort
{
	public new OpcClientSecChannelOptions Options { get; set; } = new OpcClientSecChannelOptions();
}
[RxPlatformEventType(nodeId: "1:i:201326814",  directory: "/sys/types/opc",  name: "OpcEventBase")]
public class OpcEventBase
{
}
[RxPlatformMapperType(nodeId: "1:i:201326753",  directory: "/sys/types/opc",  name: "OpcMapperBase")]
public class OpcMapperBase : ExternMapper
{
}
[RxPlatformMapperType(nodeId: "1:i:201326806",  directory: "/sys/types/opc",  name: "OpcMethodMapperBase")]
public class OpcMethodMapperBase : ExternMethodMapper
{
}
[RxPlatformPortType(nodeId: "1:i:201326720",  directory: "/sys/types/opc",  name: "OpcSecBase")]
public class OpcSecBase : ConnectionTransportPort
{
	public new OpcSecChannelOptions Options { get; set; } = new OpcSecChannelOptions();
}
[RxPlatformPortType(nodeId: "1:i:201326723",  directory: "/sys/types/opc",  name: "OpcServerBase")]
public class OpcServerBase : ApplicationPort
{
	public new OpcServerOptions Options { get; set; } = new OpcServerOptions();
	public OpcEndpointBindData Bind { get; set; } = new OpcEndpointBindData();
}
[RxPlatformPortType(nodeId: "1:i:201326743",  directory: "/sys/types/opc",  name: "OpcSimpleBinClient")]
public class OpcSimpleBinClient : OpcSimpleClient
{
}
[RxPlatformPortType(nodeId: "1:i:201326722",  directory: "/sys/types/opc",  name: "OpcSimpleBinServer")]
public class OpcSimpleBinServer : OpcSimpleServer
{
}
[RxPlatformPortType(nodeId: "1:i:201326749",  directory: "/sys/types/opc",  name: "OpcSimpleClient")]
public class OpcSimpleClient : OpcClientBase
{
}
public class OpcSimpleClientConnection : PortReference
{
	protected OpcSimpleClientConnection(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public OpcSimpleClientConnection()
		: base("1:i:201326750", "/sys/types/opc", "OpcSimpleClientConnection")
	{
	}

}
[RxPlatformEventType(nodeId: "1:i:201326815",  directory: "/sys/types/opc",  name: "OpcSimpleEvent")]
public class OpcSimpleEvent : OpcEventBase
{
	public int Namespace { get; set; } = 2;
	public string SimplePath { get; set; } = "";
	public uint NumericId { get; set; } = 0;
}
[RxPlatformMapperType(nodeId: "1:i:201326752",  directory: "/sys/types/opc",  name: "OpcSimpleMapper")]
public class OpcSimpleMapper : OpcMapperBase
{
	public string SimplePath { get; set; } = "";
	public uint NumericId { get; set; } = 0;
}
[RxPlatformMapperType(nodeId: "1:i:201326802",  directory: "/sys/types/opc",  name: "OpcSimpleMethodMapper")]
public class OpcSimpleMethodMapper : OpcMethodMapperBase
{
	public string SimplePath { get; set; } = "";
	public uint NumericId { get; set; } = 0;
}
[RxPlatformPortType(nodeId: "1:i:201326748",  directory: "/sys/types/opc",  name: "OpcSimpleServer")]
public class OpcSimpleServer : OpcServerBase
{
}
public class OpcSimpleServerConnection : PortReference
{
	protected OpcSimpleServerConnection(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public OpcSimpleServerConnection()
		: base("1:i:201326751", "/sys/types/opc", "OpcSimpleServerConnection")
	{
	}

}
[RxPlatformSourceType(nodeId: "1:i:201326758",  directory: "/sys/types/opc",  name: "OpcSimpleSource")]
public class OpcSimpleSource : OpcSourceBase
{
	public int Namespace { get; set; } = 2;
	public string SimplePath { get; set; } = "";
	public uint NumericId { get; set; } = 0;
	public byte AttrId { get; set; } = 13;
}
[RxPlatformSourceType(nodeId: "1:i:201326757",  directory: "/sys/types/opc",  name: "OpcSourceBase")]
public class OpcSourceBase : ExternSource
{
}
[RxPlatformStructType(nodeId: "1:i:201326781",  directory: "/sys/types/mqtt",  name: "MqttClientOptions")]
public class MqttClientOptions : PortOptions
{
	public string TopicBase { get; set; } = "";
	public uint PublishTimeBuffer { get; set; } = 50;
	public string ClientID { get; set; } = "";
	public ushort KeepAlive { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326800",  directory: "/sys/types/mqtt",  name: "MqttClientStatus")]
public class MqttClientStatus : PortStatusData
{
	public bool Connected { get; set; } = false;
	public ulong Published { get; set; } = 0;
	public ulong Received { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326854",  directory: "/sys/types/mqtt",  name: "MqttDisplayOptions")]
public class MqttDisplayOptions
{
	public string Topic { get; set; } = "";
	public byte QoS { get; set; } = 0;
	public bool Retain { get; set; } = true;
	public uint HoldTime { get; set; } = 200;
	public string Port { get; set; } = "";
	public string BrokerUrl { get; set; } = "ws://~/mqtt";
}
[RxPlatformStructType(nodeId: "1:i:201326788",  directory: "/sys/types/mqtt",  name: "MqttEndpointBindData")]
public class MqttEndpointBindData
{
	public string Address { get; set; } = "";
}
[RxPlatformEventType(nodeId: "1:i:201326839",  directory: "/sys/types/mqtt",  name: "MqttEventBase")]
public class MqttEventBase
{
	public string Topic { get; set; } = "";
	public byte QoS { get; set; } = 1;
}
[RxPlatformMapperType(nodeId: "1:i:201326836",  directory: "/sys/types/mqtt",  name: "MqttEventMapperBase")]
public class MqttEventMapperBase : ExternEventMapper
{
	public string Topic { get; set; } = "";
	public string DataTopic { get; set; } = "";
	public byte QoS { get; set; } = 1;
	public bool Retain { get; set; } = true;
	public uint HoldTime { get; set; } = 0;
}
[RxPlatformMapperType(nodeId: "1:i:201326794",  directory: "/sys/types/mqtt",  name: "MqttMapperBase")]
public class MqttMapperBase : ExternMapper
{
	public string Topic { get; set; } = "";
	public string DataTopic { get; set; } = "";
	public byte QoS { get; set; } = 1;
	public bool Retain { get; set; } = true;
	public uint HoldTime { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326785",  directory: "/sys/types/mqtt",  name: "MqttServerOptions")]
public class MqttServerOptions : PortOptions
{
	public ushort MaxSessExpiry { get; set; } = 120;
	public ushort MinKeepAlive { get; set; } = 60;
}
[RxPlatformStructType(nodeId: "1:i:201326801",  directory: "/sys/types/mqtt",  name: "MqttServerStatus")]
public class MqttServerStatus : PortStatusData
{
	public ulong Published { get; set; } = 0;
	public ulong Received { get; set; } = 0;
}
[RxPlatformEventType(nodeId: "1:i:201326841",  directory: "/sys/types/mqtt",  name: "MqttSimpleBrokerEvent")]
public class MqttSimpleBrokerEvent : MqttEventBase
{
}
[RxPlatformMapperType(nodeId: "1:i:201326838",  directory: "/sys/types/mqtt",  name: "MqttSimpleBrokerEventMapper")]
public class MqttSimpleBrokerEventMapper : MqttEventMapperBase
{
	public string JSONFormat { get; set; } = "{ 'val' : @val }";
	public new string DataTopic { get; set; } = "";
}
[RxPlatformMapperType(nodeId: "1:i:201326798",  directory: "/sys/types/mqtt",  name: "MqttSimpleBrokerMapper")]
public class MqttSimpleBrokerMapper : MqttMapperBase
{
	public string JSONFormat { get; set; } = "{ 'val' : @val }";
}
[RxPlatformSourceType(nodeId: "1:i:201326799",  directory: "/sys/types/mqtt",  name: "MqttSimpleBrokerSource")]
public class MqttSimpleBrokerSource : MqttSourceBase
{
	public string ValuePath { get; set; } = "val";
	public string TimePath { get; set; } = "";
	public string QualityPath { get; set; } = "";
}
[RxPlatformPortType(nodeId: "1:i:201326782",  directory: "/sys/types/mqtt",  name: "MqttSimpleClient")]
public class MqttSimpleClient : ApplicationPort
{
	public new MqttClientStatus Status { get; set; } = new MqttClientStatus();
	public new MqttClientOptions Options { get; set; } = new MqttClientOptions();
}
public class MqttSimpleClientConnection : PortReference
{
	protected MqttSimpleClientConnection(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public MqttSimpleClientConnection()
		: base("1:i:201326783", "/sys/types/mqtt", "MqttSimpleClientConnection")
	{
	}

}
[RxPlatformEventType(nodeId: "1:i:201326840",  directory: "/sys/types/mqtt",  name: "MqttSimpleEvent")]
public class MqttSimpleEvent : MqttEventBase
{
}
[RxPlatformMapperType(nodeId: "1:i:201326837",  directory: "/sys/types/mqtt",  name: "MqttSimpleEventMapper")]
public class MqttSimpleEventMapper : MqttEventMapperBase
{
	public bool Pretty { get; set; } = false;
}
[RxPlatformMapperType(nodeId: "1:i:201326795",  directory: "/sys/types/mqtt",  name: "MqttSimpleMapper")]
public class MqttSimpleMapper : MqttMapperBase
{
	public string JSONFormat { get; set; } = "{ 'val' : @val }";
}
[RxPlatformPortType(nodeId: "1:i:201326786",  directory: "/sys/types/mqtt",  name: "MqttSimpleServer")]
public class MqttSimpleServer : ApplicationPort
{
	public new MqttServerStatus Status { get; set; } = new MqttServerStatus();
	public new MqttServerOptions Options { get; set; } = new MqttServerOptions();
}
public class MqttSimpleServerConnection : PortReference
{
	protected MqttSimpleServerConnection(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public MqttSimpleServerConnection()
		: base("1:i:201326787", "/sys/types/mqtt", "MqttSimpleServerConnection")
	{
	}

}
[RxPlatformSourceType(nodeId: "1:i:201326797",  directory: "/sys/types/mqtt",  name: "MqttSimpleSource")]
public class MqttSimpleSource : MqttSourceBase
{
	public string ValuePath { get; set; } = "val";
	public string TimePath { get; set; } = "";
	public string QualityPath { get; set; } = "";
}
[RxPlatformSourceType(nodeId: "1:i:201326796",  directory: "/sys/types/mqtt",  name: "MqttSourceBase")]
public class MqttSourceBase : ExternSource
{
	public string Topic { get; set; } = "";
	public byte QoS { get; set; } = 1;
}
[RxPlatformPortType(nodeId: "1:i:201326847",  directory: "/sys/types/xml",  name: "XMLPort")]
public class XMLPort : ApplicationPort
{
	public new XMLPortOptions Options { get; set; } = new XMLPortOptions();
}
[RxPlatformStructType(nodeId: "1:i:201326849",  directory: "/sys/types/xml",  name: "XMLPortOptions")]
public class XMLPortOptions : PortOptions
{
	public string AddrXMLPath { get; set; } = "";
}
[RxPlatformSourceType(nodeId: "1:i:201326851",  directory: "/sys/types/xml",  name: "XMLSource")]
public class XMLSource : ExternSource
{
	public string XMLPath { get; set; } = "";
	public string XMLAddr { get; set; } = "";
}
[RxPlatformPortType(nodeId: "1:i:201326846",  directory: "/sys/types/json",  name: "JSONPort")]
public class JSONPort : ApplicationPort
{
}
[RxPlatformStructType(nodeId: "1:i:201326691",  directory: "/sys/types/support",  name: "BridgePortOptions")]
public class BridgePortOptions : PortOptions
{
}
[RxPlatformVariableType(nodeId: "1:i:201326822",  directory: "/sys/types/support",  name: "BridgeVariable")]
public class BridgeVariable<T>
{
	public T? _ { get; init; } = default;

	public byte InputsSelection { get; set; } = 0;
	public bool SequentialWrite { get; set; } = false;
	public bool SingleSuccess { get; set; } = true;
	public bool AckFromInput { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326686",  directory: "/sys/types/support",  name: "ClientPortStatusData")]
public class ClientPortStatusData : PortStatusData
{
	public bool Connected { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326629",  directory: "/sys/types/support",  name: "ClientTimeoutsData")]
public class ClientTimeoutsData : TimeoutsData
{
	public uint ReceiveTimeout { get; set; } = 10000;
	public uint SendTimeout { get; set; } = 1000;
	public uint ConnectTimeout { get; set; } = 2000;
	public uint ReconnectTimeout { get; set; } = 5000;
	public uint LinearReconnectTimeout { get; set; } = 5000;
	public uint MaxReconnectTimeout { get; set; } = 5000;
}
[RxPlatformVariableType(nodeId: "1:i:201326821",  directory: "/sys/types/support",  name: "ComplexIOVariable")]
public class ComplexIOVariable<T>
{
	public T? _ { get; init; } = default;

	public byte InputsSelection { get; set; } = 0;
	public bool SequentialWrite { get; set; } = false;
	public bool SingleSuccess { get; set; } = true;
	public bool AckFromInput { get; set; } = false;
}
[RxPlatformVariableType(nodeId: "1:i:201326819",  directory: "/sys/types/support",  name: "ComplexInputVariable")]
public class ComplexInputVariable<T>
{
	public T? _ { get; init; } = default;

	public byte InputsSelection { get; set; } = 0;
}
[RxPlatformVariableType(nodeId: "1:i:201326820",  directory: "/sys/types/support",  name: "ComplexOutputVariable")]
public class ComplexOutputVariable<T>
{
	public T? _ { get; init; } = default;

	public bool SequentialWrite { get; set; } = false;
	public bool SingleSuccess { get; set; } = true;
	public bool AckFromInput { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326708",  directory: "/sys/types/support",  name: "DisplayResource")]
public class DisplayResource
{
}
[RxPlatformStructType(nodeId: "1:i:201326710",  directory: "/sys/types/support",  name: "DisplayStatus")]
public class DisplayStatus
{
	public long Req { get; set; } = 0;
	public long Failed { get; set; } = 0;
	public float LastReqTime { get; set; } = 0;
	public float MaxReqTime { get; set; } = 0;
}
[RxPlatformEventType(nodeId: "1:i:201326867",  directory: "/sys/types/support",  name: "DotNetEvent")]
public class DotNetEvent
{
}
[RxPlatformMapperType(nodeId: "1:i:201326869",  directory: "/sys/types/support",  name: "DotNetMapper")]
public class DotNetMapper : VariableMapper
{
}
public class DotNetRelation : RxPlatformRelationAttribute
{
	protected DotNetRelation(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public DotNetRelation()
		: base("1:i:201326874", "/sys/types/support", "DotNetRelation")
	{
	}

}
[RxPlatformSourceType(nodeId: "1:i:201326868",  directory: "/sys/types/support",  name: "DotNetSource")]
public class DotNetSource : VariableSource
{
}
[RxPlatformStructType(nodeId: "1:i:201326870",  directory: "/sys/types/support",  name: "DotNetStruct")]
public class DotNetStruct
{
}
[RxPlatformStructType(nodeId: "1:i:201326762",  directory: "/sys/types/support",  name: "EthernetPortOptions")]
public class EthernetPortOptions : PortOptions
{
	public string Port { get; set; } = "";
	public ushort[] EtherTypes { get; set; } = [];
}
[RxPlatformMapperType(nodeId: "1:i:201326810",  directory: "/sys/types/support",  name: "EventMapper")]
public class EventMapper
{
}
[RxPlatformMapperType(nodeId: "1:i:201326811",  directory: "/sys/types/support",  name: "ExternEventMapper")]
public class ExternEventMapper : EventMapper
{
	public string Port { get; set; } = "";
}
[RxPlatformMapperType(nodeId: "1:i:201326643",  directory: "/sys/types/support",  name: "ExternMapper")]
public class ExternMapper : VariableMapper
{
	public string Port { get; set; } = "";
}
[RxPlatformMapperType(nodeId: "1:i:201326805",  directory: "/sys/types/support",  name: "ExternMethodMapper")]
public class ExternMethodMapper : MethodMapper
{
	public string Port { get; set; } = "";
}
[RxPlatformSourceType(nodeId: "1:i:201326644",  directory: "/sys/types/support",  name: "ExternSource")]
public class ExternSource : VariableSource
{
	public string Port { get; set; } = "";
}
[RxPlatformMapperType(nodeId: "1:i:201326669",  directory: "/sys/types/support",  name: "ExternStructuralMapper")]
public class ExternStructuralMapper : StructuralMapper
{
	public string Port { get; set; } = "";
}
[RxPlatformSourceType(nodeId: "1:i:201326670",  directory: "/sys/types/support",  name: "ExternStructuralSource")]
public class ExternStructuralSource : StructuralSource
{
	public string Port { get; set; } = "";
}
[RxPlatformStructType(nodeId: "1:i:201326624",  directory: "/sys/types/support",  name: "ExternalPortStatusData")]
public class ExternalPortStatusData : PortStatusData
{
	public long RxBytes { get; set; } = 0;
	public long TxBytes { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326845",  directory: "/sys/types/support",  name: "FilePortOptions")]
public class FilePortOptions : PortOptions
{
	public string DirectoryPath { get; set; } = "";
	public string FileFilter { get; set; } = "*";
	public int FileTimeout { get; set; } = 300000;
}
[RxPlatformStructType(nodeId: "1:i:201326825",  directory: "/sys/types/support",  name: "HttpAddressingPortOptions")]
public class HttpAddressingPortOptions : PortOptions
{
	public uint MaxPacket { get; set; } = 65536;
	public byte PathParts { get; set; } = 1;
	public bool UseHostName { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326827",  directory: "/sys/types/support",  name: "HttpHostNamePortOptions")]
public class HttpHostNamePortOptions : PortOptions
{
	public uint MaxPacket { get; set; } = 65536;
	public byte PathParts { get; set; } = 1;
	public bool UseHostName { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326625",  directory: "/sys/types/support",  name: "IPBindData")]
public class IPBindData
{
	public string IPAddress { get; set; } = "";
	public ushort IPPort { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326692",  directory: "/sys/types/support",  name: "LimiterPortOptions")]
public class LimiterPortOptions : PortOptions
{
	public int Limit { get; set; } = 1;
	public bool IgnoreZeros { get; set; } = false;
	public bool UsePacketId { get; set; } = true;
	public int QueueSize { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326765",  directory: "/sys/types/support",  name: "MACBindData")]
public class MACBindData
{
	public byte[] Address { get; set; } = new byte[0];
}
[RxPlatformStructType(nodeId: "1:i:201326687",  directory: "/sys/types/support",  name: "MasterPortStatusData")]
public class MasterPortStatusData : PortStatusData
{
	public bool Online { get; set; } = false;
	public long Reads { get; set; } = 0;
	public long Writes { get; set; } = 0;
	public long FailedReads { get; set; } = 0;
	public long FailedWrites { get; set; } = 0;
	public float LastRead { get; set; } = 0;
	public float MaxRead { get; set; } = 0;
	public float LastWrite { get; set; } = 0;
	public float MaxWrite { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326685",  directory: "/sys/types/support",  name: "MasterTimeoutsData")]
public class MasterTimeoutsData : TimeoutsData
{
	public uint ReadTimeout { get; set; } = 200;
	public uint WriteTimeout { get; set; } = 500;
	public uint ReconnectTimeout { get; set; } = 5000;
	public uint LinearReconnectTimeout { get; set; } = 5000;
	public uint MaxReconnectTimeout { get; set; } = 5000;
}
[RxPlatformMapperType(nodeId: "1:i:201326804",  directory: "/sys/types/support",  name: "MethodMapper")]
public class MethodMapper
{
}
[RxPlatformVariableType(nodeId: "1:i:201326823",  directory: "/sys/types/support",  name: "MultiplexerVariable")]
public class MultiplexerVariable<T>
{
	public T? _ { get; init; } = default;

	public sbyte Select { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326746",  directory: "/sys/types/support",  name: "OpcBinTransportOptions")]
public class OpcBinTransportOptions : PortOptions
{
	public bool Reverse { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326747",  directory: "/sys/types/support",  name: "OpcClientBinTransportOptions")]
public class OpcClientBinTransportOptions : PortOptions
{
	public bool Reverse { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326742",  directory: "/sys/types/support",  name: "OpcClientOptions")]
public class OpcClientOptions : PortOptions
{
	public bool ReverseConn { get; set; } = false;
	public string AppUri { get; set; } = "";
	public string AppName { get; set; } = "";
	public string ServerUri { get; set; } = "";
	public uint PublishInterval { get; set; } = 200;
}
[RxPlatformStructType(nodeId: "1:i:201326740",  directory: "/sys/types/support",  name: "OpcClientSecChannelOptions")]
public class OpcClientSecChannelOptions : PortOptions
{
}
[RxPlatformStructType(nodeId: "1:i:201326755",  directory: "/sys/types/support",  name: "OpcEndpointBindData")]
public class OpcEndpointBindData
{
	public string Endpoint { get; set; } = "";
}
[RxPlatformStructType(nodeId: "1:i:201326744",  directory: "/sys/types/support",  name: "OpcSecChannelOptions")]
public class OpcSecChannelOptions : PortOptions
{
}
[RxPlatformStructType(nodeId: "1:i:201326739",  directory: "/sys/types/support",  name: "OpcServerOptions")]
public class OpcServerOptions : PortOptions
{
	public string AppUri { get; set; } = "";
	public string AppName { get; set; } = "";
	public bool ReverseConn { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326861",  directory: "/sys/types/support",  name: "PathBindData")]
public class PathBindData
{
	public string Path { get; set; } = "";
}
[RxPlatformStructType(nodeId: "1:i:201326767",  directory: "/sys/types/support",  name: "PeerEndpoint")]
public class PeerEndpoint
{
	public string Url { get; set; } = "";
	public string Name { get; set; } = "";
}
[RxPlatformStructType(nodeId: "1:i:201326768",  directory: "/sys/types/support",  name: "PeerStatus")]
public class PeerStatus
{
	public bool Online { get; set; } = false;
	public string Version { get; set; } = "";
}
[RxPlatformSourceType(nodeId: "1:i:201326665",  directory: "/sys/types/support",  name: "PlatformSource")]
public class PlatformSource : VariableSource
{
	public string Path { get; set; } = "";
}
[RxPlatformStructType(nodeId: "1:i:201326630",  directory: "/sys/types/support",  name: "PoolData")]
public class PoolData
{
	public ushort Threads { get; set; } = 0;
	public double LastProcTime { get; set; } = 0;
	public uint QueueSize { get; set; } = 0;
	public double MaxProcTime { get; set; } = 0;
	public uint MaxQueueSize { get; set; } = 0;
}
[RxPlatformSourceType(nodeId: "1:i:201326645",  directory: "/sys/types/support",  name: "RegisterSource")]
public class RegisterSource : VariableSource
{
	public bool Persist { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326690",  directory: "/sys/types/support",  name: "RouterPortOptions")]
public class RouterPortOptions : PortOptions
{
	public bool Initiator { get; set; } = false;
	public bool Listener { get; set; } = false;
	public uint SessionTimeout { get; set; } = 2000;
}
[RxPlatformStructType(nodeId: "1:i:201326631",  directory: "/sys/types/support",  name: "RuntimeData")]
public class RuntimeData
{
	public ushort IOThreads { get; set; } = 0;
	public ushort Workers { get; set; } = 0;
	public bool CalcTimer { get; set; } = false;
	public uint PointsCount { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326702",  directory: "/sys/types/support",  name: "STXETXPortOptions")]
public class STXETXPortOptions : PortOptions
{
	public int MaxPacketSize { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326699",  directory: "/sys/types/support",  name: "SerialPortOptions")]
public class SerialPortOptions : PortOptions
{
	public string Port { get; set; } = "";
	public uint BaudRate { get; set; } = 19200;
	public byte DataBits { get; set; } = 8;
	public byte StopBits { get; set; } = 0;
	public byte Parity { get; set; } = 0;
	public bool Handshake { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326688",  directory: "/sys/types/support",  name: "ServerTimeoutsData")]
public class ServerTimeoutsData : TimeoutsData
{
	public uint ReceiveTimeout { get; set; } = 10000;
	public uint SendTimeout { get; set; } = 1000;
}
[RxPlatformVariableType(nodeId: "1:i:201326818",  directory: "/sys/types/support",  name: "SimpleVariable")]
public class SimpleVariable<T>
{
	public T? _ { get; init; } = default;

}
[RxPlatformStructType(nodeId: "1:i:201326817",  directory: "/sys/types/support",  name: "SizeLimiterPortOptions")]
public class SizeLimiterPortOptions : PortOptions
{
	public int Limit { get; set; } = 65536;
}
[RxPlatformMapperType(nodeId: "1:i:201326661",  directory: "/sys/types/support",  name: "StructuralMapper")]
public class StructuralMapper
{
	public bool Root { get; set; } = false;
}
[RxPlatformSourceType(nodeId: "1:i:201326663",  directory: "/sys/types/support",  name: "StructuralSource")]
public class StructuralSource
{
	public bool Root { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326852",  directory: "/sys/types/support",  name: "TcpPortOptions")]
public class TcpPortOptions : PortOptions
{
	public uint KeepAlive { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326640",  directory: "/sys/types/support",  name: "ThreadData")]
public class ThreadData
{
	public uint ThreadId { get; set; } = 0;
	public ushort Queue { get; set; } = 0;
	public ushort MaxQueue { get; set; } = 0;
}
[RxPlatformStructType(nodeId: "1:i:201326628",  directory: "/sys/types/support",  name: "TimeoutsData")]
public class TimeoutsData
{
}
[RxPlatformStructType(nodeId: "1:i:201326775",  directory: "/sys/types/support",  name: "TlsPortOptions")]
public class TlsPortOptions : PortOptions
{
	public string Certificate { get; set; } = "host";
	public bool RequireClientAuth { get; set; } = true;
	public bool Initiator { get; set; } = true;
}
[RxPlatformStructType(nodeId: "1:i:201326776",  directory: "/sys/types/support",  name: "TlsPortStatus")]
public class TlsPortStatus : PortStatusData
{
	public bool SecActive { get; set; } = false;
}
[RxPlatformStructType(nodeId: "1:i:201326777",  directory: "/sys/types/support",  name: "TlsPortTimeouts")]
public class TlsPortTimeouts : TimeoutsData
{
	public uint TokenTimeout { get; set; } = 300000;
}
[RxPlatformMapperType(nodeId: "1:i:201326803",  directory: "/sys/types/support",  name: "VariableMapper")]
public class VariableMapper
{
	public byte ValueType { get; set; } = 0;
}
[RxPlatformSourceType(nodeId: "1:i:201326809",  directory: "/sys/types/support",  name: "VariableSource")]
public class VariableSource
{
	public byte ValueType { get; set; } = 0;
}
[RxPlatformSourceType(nodeId: "1:i:201326656",  directory: "/sys/types/simulation",  name: "SimulationSource")]
public class SimulationSource : VariableSource
{
}
public class Application : RxPlatformRelationAttribute
{
	protected Application(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public Application()
		: base("1:i:16", "/sys/types/relations", "Application")
	{
	}

}
public class Domain : RxPlatformRelationAttribute
{
	protected Domain(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public Domain()
		: base("1:i:18", "/sys/types/relations", "Domain")
	{
	}

}
public class PortApp : RxPlatformRelationAttribute
{
	protected PortApp(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public PortApp()
		: base("1:i:17", "/sys/types/relations", "PortApp")
	{
	}

}
public class PortReference : RxPlatformRelationAttribute
{
	protected PortReference(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public PortReference()
		: base("1:i:23", "/sys/types/relations", "PortReference")
	{
	}

}
public class PortStack : RxPlatformRelationAttribute
{
	protected PortStack(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public PortStack()
		: base("1:i:15", "/sys/types/relations", "PortStack")
	{
	}

}
[RxPlatformObjectType(nodeId: "1:i:201326594",  directory: "/sys/types/term",  name: "CmdManagerType")]
public class CmdManagerType : InternalObjectType
{
}
[RxPlatformPortType(nodeId: "1:i:201326615",  directory: "/sys/types/term",  name: "VT100Port")]
public class VT100Port : ApplicationPort
{
}
[RxPlatformStructType(nodeId: "1:i:201326707",  directory: "/sys/types/http",  name: "HttpDisplayResource")]
public class HttpDisplayResource : DisplayResource
{
	public string[] DisplayFiles { get; set; } = [];
}
[RxPlatformStructType(nodeId: "1:i:201326711",  directory: "/sys/types/http",  name: "HttpDisplayStatus")]
public class HttpDisplayStatus : DisplayStatus
{
	public string LastError { get; set; } = "OK";
}
[RxPlatformStructType(nodeId: "1:i:201326712",  directory: "/sys/types/http",  name: "StaticHttpDisplayResource")]
public class StaticHttpDisplayResource : HttpDisplayResource
{
}
}
// Generated on:Tuesday, December 9, 2025  3:20:16 PM
