// This code is generated by {rx-platform} Code Generation Tool
// DO NOT MODIFY THIS CODE, it can be recreated

using ENSACO.RxPlatform.Attributes;
using ENSACO.RxPlatform.Model.System;

namespace ENSACO.RxPlatform.Model.Modbus
{
[RxPlatformDataType(nodeId: "1:g:cce8532b-3ff2-49f3-b674-6b3dde39e837",  directory: "/sys/plugins/modbus/data",  name: "ModbusResponse")]
public class ModbusResponse
{
	public byte Result { get; set; } = 255;
}
[RxPlatformDataType(nodeId: "1:g:d3116d76-eda5-476f-86c2-b038b1c1cfbc",  directory: "/sys/plugins/modbus/data",  name: "ReadHRRequest")]
public class ReadHRRequest
{
	public ushort Addr { get; set; } = 0;
	public ushort Count { get; set; } = 1;
}
[RxPlatformDataType(nodeId: "1:g:ca133c1e-3e99-481c-8fec-d2a34521bcd6",  directory: "/sys/plugins/modbus/data",  name: "ReadHRResponse")]
public class ReadHRResponse : ModbusResponse
{
	public ushort[] Values { get; set; } = [];
}
[RxPlatformDataType(nodeId: "1:g:493893ec-b485-4070-907b-01afc075f676",  directory: "/sys/plugins/modbus/data",  name: "WriteSingleHRRequest")]
public class WriteSingleHRRequest
{
	public ushort Addr { get; set; } = 0;
	public ushort Value { get; set; } = 1;
}
[RxPlatformStructType(nodeId: "1:g:a5ed85a3-0641-40d8-95a5-3efda9d0eb21",  directory: "/sys/plugins/modbus/transport",  name: "ModbusData")]
public class ModbusData
{
	public byte Address { get; set; } = 0;
}
[RxPlatformPortType(nodeId: "1:g:ac0183ae-983c-40a6-b53e-1f328eaa0fc2",  directory: "/sys/plugins/modbus/transport",  name: "ModbusRTUMaster")]
public class ModbusRTUMaster : TransportPort
{
}
[RxPlatformPortType(nodeId: "1:g:d23d1c79-9328-456e-8181-e11aaeae961b",  directory: "/sys/plugins/modbus/transport",  name: "ModbusRTUSlave")]
public class ModbusRTUSlave : TransportPort
{
}
[RxPlatformPortType(nodeId: "1:g:be2a48f6-6758-43f0-9691-110582ec8b5a",  directory: "/sys/plugins/modbus/transport",  name: "ModbusTCPMaster")]
public class ModbusTCPMaster : TransportPort
{
}
[RxPlatformPortType(nodeId: "1:g:4165c81e-0146-4670-8479-1dd2808b35dd",  directory: "/sys/plugins/modbus/transport",  name: "ModbusTCPSlave")]
public class ModbusTCPSlave : TransportPort
{
}
public class ModbusCoilSource : ModbusSourceBase
{
	public ModbusCoilSource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true)
		: base(nodeId == "" ? "1:g:8aed3480-db70-4910-afc8-f9491977bfde" : nodeId, directory == "" ? "/sys/plugins/modbus/master" : directory, name == "" ? "ModbusCoilSource" : name, Element == "" ? "ModbusCoilSource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
	}

}
public class ModbusHoldingRegisterSource : ModbusSourceBase
{
	public ModbusHoldingRegisterSource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true, byte BitOffset = 0, byte StringLen = 8, bool SwapBytes = false, bool SwapWords = false)
		: base(nodeId == "" ? "1:g:f628eb7c-aafd-4a9a-a28d-c69ba5726ba2" : nodeId, directory == "" ? "/sys/plugins/modbus/master" : directory, name == "" ? "ModbusHoldingRegisterSource" : name, Element == "" ? "ModbusHoldingRegisterSource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
		this.BitOffset = BitOffset;this.StringLen = StringLen;this.SwapBytes = SwapBytes;this.SwapWords = SwapWords;

	}

	public byte BitOffset { get; set; } = 0;
	public byte StringLen { get; set; } = 8;
	public bool SwapBytes { get; set; } = false;
	public bool SwapWords { get; set; } = false;
}
public class ModbusInputRegisterSource : ModbusSourceBase
{
	public ModbusInputRegisterSource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true, byte BitOffset = 0, byte StringLen = 8, bool SwapBytes = false, bool SwapWords = false)
		: base(nodeId == "" ? "1:g:2b8d21ea-e73c-4ff5-b111-09ea0c840f8f" : nodeId, directory == "" ? "/sys/plugins/modbus/master" : directory, name == "" ? "ModbusInputRegisterSource" : name, Element == "" ? "ModbusInputRegisterSource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
		this.BitOffset = BitOffset;this.StringLen = StringLen;this.SwapBytes = SwapBytes;this.SwapWords = SwapWords;

	}

	public byte BitOffset { get; set; } = 0;
	public byte StringLen { get; set; } = 8;
	public bool SwapBytes { get; set; } = false;
	public bool SwapWords { get; set; } = false;
}
public class ModbusInputSource : ModbusSourceBase
{
	public ModbusInputSource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true)
		: base(nodeId == "" ? "1:g:4c8215c7-5531-474a-988f-c2eab45d9c13" : nodeId, directory == "" ? "/sys/plugins/modbus/master" : directory, name == "" ? "ModbusInputSource" : name, Element == "" ? "ModbusInputSource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
	}

}
[RxPlatformPortType(nodeId: "1:g:ac064be0-52b6-4d41-b607-db0f8987207b",  directory: "/sys/plugins/modbus/master",  name: "ModbusMasterConnection")]
public class ModbusMasterConnection : ApplicationPort
{
	public new ModbusMasterData Options { get; set; } = new ModbusMasterData();
	public new ModbusMasterStatus Status { get; set; } = new ModbusMasterStatus();
	public MasterTimeoutsData Timeouts { get; set; } = new MasterTimeoutsData();
	public ModbusData Connect { get; set; } = new ModbusData();
}
[RxPlatformStructType(nodeId: "1:g:4e69d36b-031a-4388-b778-c86f95142cf7",  directory: "/sys/plugins/modbus/master",  name: "ModbusMasterData")]
public class ModbusMasterData : PortOptions
{
	public ushort MaxInputRegisters { get; set; } = 125;
	public ushort MaxHoldingRegisters { get; set; } = 125;
	public ushort MaxCoils { get; set; } = 2000;
	public ushort MaxInputs { get; set; } = 2000;
	public ushort OptimizeRegisters { get; set; } = 5;
	public ushort OptimizeBits { get; set; } = 160;
	public uint ScanRate { get; set; } = 200;
	public bool WordSwap { get; set; } = false;
	public uint WriteRetries { get; set; } = 1;
	public uint WriteRetryMin { get; set; } = 10;
	public uint WriteRetryMax { get; set; } = 20;
	public bool ReadDeviceId { get; set; } = true;
}
public class ModbusMasterRelation : PortReference
{
	protected ModbusMasterRelation(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public ModbusMasterRelation()
		: base("1:g:79709ab0-1894-47f3-97a2-328f1835fd88", "/sys/plugins/modbus/master", "ModbusMasterRelation")
	{
	}

}
[RxPlatformStructType(nodeId: "1:g:a3392268-e897-4c52-8d3b-2165ec8210aa",  directory: "/sys/plugins/modbus/master",  name: "ModbusMasterStatus")]
public class ModbusMasterStatus : MasterPortStatusData
{
	public byte LastError { get; set; } = 0;
	public string Vendor { get; set; } = "";
	public string Product { get; set; } = "";
	public string Application { get; set; } = "";
}
public class ModbusSourceBase : ExternSource
{
	public ModbusSourceBase(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true, ushort Address = 0)
		: base(nodeId == "" ? "1:g:f58e5ba7-3ec2-4953-a27b-45ede5d6bd47" : nodeId, directory == "" ? "/sys/plugins/modbus/master" : directory, name == "" ? "ModbusSourceBase" : name, Element == "" ? "ModbusSourceBase" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
		this.Address = Address;

	}

	public ushort Address { get; set; } = 0;
}
public class ModbusStructSource : ExternStructuralSource
{
	public ModbusStructSource(string nodeId = "", string directory = "", string name = "", string Element = "", bool Input = true, bool Output = false, bool Sim = false, bool Proc = true, ushort InputRegAddress = 0, ushort InputAddress = 0, ushort HoldingRegAddress = 0, ushort CoilAddress = 0)
		: base(nodeId == "" ? "1:g:7ad41d69-6bb3-47b7-bee8-d6ad8ab4917a" : nodeId, directory == "" ? "/sys/plugins/modbus/master" : directory, name == "" ? "ModbusStructSource" : name, Element == "" ? "ModbusStructSource" : Element, Input : Input, Output: Output, Sim: Sim, Proc: Proc)
	{
		this.InputRegAddress = InputRegAddress;this.InputAddress = InputAddress;this.HoldingRegAddress = HoldingRegAddress;this.CoilAddress = CoilAddress;

	}

	public ushort InputRegAddress { get; set; } = 0;
	public ushort InputAddress { get; set; } = 0;
	public ushort HoldingRegAddress { get; set; } = 0;
	public ushort CoilAddress { get; set; } = 0;
}
public class ModbusCoil : ModbusMapperBase
{
	public ModbusCoil(string nodeId = "", string directory = "", string name = "", string Element = "", bool Write = false, bool Read = true, bool Sim = false, bool Proc = true, bool WriteThrough = true)
		: base(nodeId == "" ? "1:g:32c6e09d-f6fc-4d1d-8dcd-d40b1603adea" : nodeId, directory == "" ? "/sys/plugins/modbus/slave" : directory, name == "" ? "ModbusCoil" : name, Element == "" ? "ModbusCoil" : Element, Write : Write, Read: Read, Sim: Sim, Proc: Proc)
	{
		this.WriteThrough = WriteThrough;

	}

	public bool WriteThrough { get; set; } = true;
}
public class ModbusHoldingRegister : ModbusMapperBase
{
	public ModbusHoldingRegister(string nodeId = "", string directory = "", string name = "", string Element = "", bool Write = false, bool Read = true, bool Sim = false, bool Proc = true, byte BitOffset = 0, bool WriteThrough = true, byte StringLen = 8, bool SwapBytes = false, bool SwapWords = false)
		: base(nodeId == "" ? "1:g:7e3a32e5-cf4d-4471-843b-36ef5db94360" : nodeId, directory == "" ? "/sys/plugins/modbus/slave" : directory, name == "" ? "ModbusHoldingRegister" : name, Element == "" ? "ModbusHoldingRegister" : Element, Write : Write, Read: Read, Sim: Sim, Proc: Proc)
	{
		this.BitOffset = BitOffset;this.WriteThrough = WriteThrough;this.StringLen = StringLen;this.SwapBytes = SwapBytes;this.SwapWords = SwapWords;

	}

	public byte BitOffset { get; set; } = 0;
	public bool WriteThrough { get; set; } = true;
	public byte StringLen { get; set; } = 8;
	public bool SwapBytes { get; set; } = false;
	public bool SwapWords { get; set; } = false;
}
public class ModbusInput : ModbusMapperBase
{
	public ModbusInput(string nodeId = "", string directory = "", string name = "", string Element = "", bool Write = false, bool Read = true, bool Sim = false, bool Proc = true)
		: base(nodeId == "" ? "1:g:7530f186-881f-40d8-bbd5-40c702465900" : nodeId, directory == "" ? "/sys/plugins/modbus/slave" : directory, name == "" ? "ModbusInput" : name, Element == "" ? "ModbusInput" : Element, Write : Write, Read: Read, Sim: Sim, Proc: Proc)
	{
	}

}
public class ModbusInputRegister : ModbusMapperBase
{
	public ModbusInputRegister(string nodeId = "", string directory = "", string name = "", string Element = "", bool Write = false, bool Read = true, bool Sim = false, bool Proc = true, byte BitOffset = 0, byte StringLen = 8, bool SwapBytes = false, bool SwapWords = false)
		: base(nodeId == "" ? "1:g:172d6fcc-5c3a-4b8e-8c5d-79d2eb60ad77" : nodeId, directory == "" ? "/sys/plugins/modbus/slave" : directory, name == "" ? "ModbusInputRegister" : name, Element == "" ? "ModbusInputRegister" : Element, Write : Write, Read: Read, Sim: Sim, Proc: Proc)
	{
		this.BitOffset = BitOffset;this.StringLen = StringLen;this.SwapBytes = SwapBytes;this.SwapWords = SwapWords;

	}

	public byte BitOffset { get; set; } = 0;
	public byte StringLen { get; set; } = 8;
	public bool SwapBytes { get; set; } = false;
	public bool SwapWords { get; set; } = false;
}
public class ModbusMapperBase : ExternMapper
{
	public ModbusMapperBase(string nodeId = "", string directory = "", string name = "", string Element = "", bool Write = false, bool Read = true, bool Sim = false, bool Proc = true, ushort Address = 0, sbyte QualityType = 0, sbyte QualityAddressType = 0, ushort QualityAddress = 0, byte QualityBitOffset = 0, byte QualityStringLen = 8)
		: base(nodeId == "" ? "1:g:54bd4120-967e-45ed-98e1-9d67b89f1df1" : nodeId, directory == "" ? "/sys/plugins/modbus/slave" : directory, name == "" ? "ModbusMapperBase" : name, Element == "" ? "ModbusMapperBase" : Element, Write : Write, Read: Read, Sim: Sim, Proc: Proc)
	{
		this.Address = Address;this.QualityType = QualityType;this.QualityAddressType = QualityAddressType;this.QualityAddress = QualityAddress;this.QualityBitOffset = QualityBitOffset;this.QualityStringLen = QualityStringLen;

	}

	public ushort Address { get; set; } = 0;
	public sbyte QualityType { get; set; } = 0;
	public sbyte QualityAddressType { get; set; } = 0;
	public ushort QualityAddress { get; set; } = 0;
	public byte QualityBitOffset { get; set; } = 0;
	public byte QualityStringLen { get; set; } = 8;
}
[RxPlatformPortType(nodeId: "1:g:3da88e1b-d4e0-4fff-911d-978f2ee78c8d",  directory: "/sys/plugins/modbus/slave",  name: "ModbusSlaveConnection")]
public class ModbusSlaveConnection : ApplicationPort
{
	public new ModbusSlaveData Options { get; set; } = new ModbusSlaveData();
	public ModbusData Bind { get; set; } = new ModbusData();
}
[RxPlatformStructType(nodeId: "1:g:10f8836e-7d10-4a14-915a-7a2385a12d59",  directory: "/sys/plugins/modbus/slave",  name: "ModbusSlaveData")]
public class ModbusSlaveData : PortOptions
{
	public string AppName { get; set; } = "AppName";
	public bool WordSwap { get; set; } = false;
}
public class ModbusSlaveRelation : PortReference
{
	protected ModbusSlaveRelation(string nodeId, string directory = "", string name = "")
		: base(nodeId, directory, name)
	{
	}

	public ModbusSlaveRelation()
		: base("1:g:bb50d710-b2ae-4a87-b384-a111713f966e", "/sys/plugins/modbus/slave", "ModbusSlaveRelation")
	{
	}

}
public class ModbusStructMapper : ExternStructuralMapper
{
	public ModbusStructMapper(string nodeId = "", string directory = "", string name = "", string Element = "", bool Write = false, bool Read = true, bool Sim = false, bool Proc = true, ushort InputRegAddress = 0, ushort InputAddress = 0, ushort HoldingRegAddress = 0, ushort CoilAddress = 0)
		: base(nodeId == "" ? "1:g:ebed32f7-1231-4ea2-852d-653a2be13ac5" : nodeId, directory == "" ? "/sys/plugins/modbus/slave" : directory, name == "" ? "ModbusStructMapper" : name, Element == "" ? "ModbusStructMapper" : Element, Write : Write, Read: Read, Sim: Sim, Proc: Proc)
	{
		this.InputRegAddress = InputRegAddress;this.InputAddress = InputAddress;this.HoldingRegAddress = HoldingRegAddress;this.CoilAddress = CoilAddress;

	}

	public ushort InputRegAddress { get; set; } = 0;
	public ushort InputAddress { get; set; } = 0;
	public ushort HoldingRegAddress { get; set; } = 0;
	public ushort CoilAddress { get; set; } = 0;
}
}
// Generated on:Friday, September 25, 2026  8:51:04 AM
